### ISSUE TITLE
publish crate

### ISSUE THREAD

**Issue by yazgoo** [r-marques/doomfire#4]
Hi,

Thanks for this awesome project.
Could you please add a license and publish this as a crate ?

I'd like to use it in https://github.com/yazgoo/blockishfire
Right now I'm including your code as a submodule https://github.com/yazgoo/blockishfire/blob/master/Cargo.toml#L11

**Comment by r-marques** [comment]
Sorry for the delay. The crate is now published in [crates.io](https://crates.io/crates/doomfire)
